# Site settings
title: Beatriz Marques
twitter_username: biarox80
name: Beatriz Marques

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://mygameprojectdesign.blogspot.com/
 - title: GitHub
   url: https://github.com/biarox 
 - title: LinkedIn
   url: https://www.linkedin.com/in/biarox/

#Any buzzword skills you want to include
skills:
 - User Research
 - Data analysis
 - Test application
 - A/B Testing
 - Sketching
 - Wireframe
 - Figma
 - Invision
 - Zeplin
 - Photoshop
 - Slack
 - Design Thinking
 - Agile methodologies
 - Scrum
 - Jira

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://mygameprojectdesign.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: UX Designer
   start: 2018
   end: Ongoing
   employer: Stefanini
   description: Stefanini is a private Brazilian multinational, service and software provider, for data processing and consulting, with more than 25,000 employees in 40 countries across the Americas, Europe, Australia, and Asia.
 - title: Community Manager
   start: 2017
   end: 2019
   employer: Gimmer
   description: Gimmer is an automated trading platform that offers bots which execute cryptocurrency trading operations such as lending, arbitrage, margin trading, etc.
 - title: UX Designer / Front end
   start: 2015
   end: 2016
   employer: Antar Qld
   description: ANTaR Qld is an independent, national network of organisations and individuals working in support of justice for Aboriginal and Torres Strait Islander peoples of Queensland, Australia, since 1997.
 - title: Art Director
   start: 2002
   end: 2014
   employer: Sinprafarmas
   description: Sinprafarmas is a labor union focused in defend the interests of the farmacists and drugstore workers.

#Education is required
education:
 - level: Associate Degree (A.Dg.)
   date: 2017
   subject: Internet Systems
   school: Faculty of Technology from Baixada Santista - FATEC
 - level: Bachelor of Science (B.Sc.)
   date: 2002
   subject: Publicity & Advertising
   school: Catholic University of Santos
 - level: Certificate (extencion course)
   date: 2015
   subject: IT and Computer Science
   school: Queensland University of Technology - QUT



#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/d13ffd884cb6aaca9dc6d859499048b6
   courses:
    - title: Agile meets Design Thinking
      link: https://www.coursera.org/learn/uva-darden-getting-started-agile?
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
      date: February 12, 2019
    - title: Human-Centered Design
      link: https://www.coursera.org/learn/human-computer-interaction?
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
      date: Ongoing
    - title: UX by Design Circuit
      link: https://www.designcircuit.co/
      optionalimage: https://i.ytimg.com/vi/TUxG8iffRBs/maxresdefault.jpg
      date: Ongoing


#List of interesting Github repo/projects to include - optional
github:
 - biarox/biarox.github.io
 - biarox/seguran

#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://avatars0.githubusercontent.com/u/1934896?s=460&v=4
   

intro: |
  Hi, I am an User Experience Designer with 4 years experience, working in technology since 2002. I have primarily worked as a Graphic Designer and then moved to Web Designer. 

  I love to work in a team. I've developed a mobile app using Xamarin, with three other colleagues, it was for an organisation that was focused on young women who recovered from cancer. My contribution to this application not only involved the creation, the name, the idea and the layout, but also organising the team, managing the tasks and presenting the project. As a result, the owner of this organisation chose our application as the best one among two other apps. This is how I feel when I deliver a project, a feeling of "mission accomplished" because I just love what I do and that's why I want to work in IT so much. I graduated in Internet Systems in December of 2017. I learned about Project Management and a lot of different programming languages such as C#, Python, Java and PHP. I love new technologies so I'm constantly going to events related to IT and also games - that is one of my hobbies. 

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Lean Inception + Design Thinking = Deep Dive</strong>: 
    <div>
    <h2>I participated in the process of development of a new product for a Brazilian payment institution. <h2><br/><br/>
    <h2>I joined the development of this product since the beginning, which allowed me to contribute to the key features by matching the user needs and the business needs.</h2>
    </div>
    <div>
    <ul>
    <li>It was a new product focused on the payment of car tolls and debts. It required some study of the Brazilian Federal laws regarding payment and research of the law from each specific state.</li>
    <li>The target audience was people that own a vehicle (cars only) and had any debts to be paid.</li>
    <li>The product was created to make the payment easier by allowing the car owners to pay their debts in instalments.</li>
    <li>The challenge was to ideate, prototype and test an MVP in a small state and after that expand the business to the entire country.</li>
    <li>My role was to support the Agile Coach in the meetings, helping with the applied methodologies, using post-its, gathering the attention of the business crew, maintaining a productive environment.</li>
    <li>I also created and delivered an interactive mockup at the end of the process using Figma.</li>
    </ul>
    </div>
    <div>
    <h2>Personas</h2>
    <p>Based on the interviews/workshop we set up twelve personas. We referred to them throughout the entire product concept process.</p>
    <ul>
    <li>We listed all the users that will have direct contact with the system, from the stakeholders, finance to the final user.</li>
    <li>We used the personas to determine what each user needed from the system, and found out how many user roles were necessary to log in to the system as well.</li>
    </ul>
    </div>


   <strong>User Testing</strong>: <h2>I participated in the process of development of a new product for a Brazilian payment institution. <h2><br/><br/>
    <h2>I joined the development of this product since the beginning, which allowed me to contribute to the key features by matching the user needs and the business needs.</h2>