# Site settings
title: Beatriz Marques
twitter_username: biarox80
name: Beatriz Marques

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/biarox 
 - title: LinkedIn
   url: https://www.linkedin.com/in/biarox/
 - title: Blog
   url: https://mygameprojectdesign.blogspot.com/
 - title: Behance
   url: https://www.behance.net/biarox

#Any buzzword skills you want to include
skills:
 - User Research
 - User tests
 - Data analysis
 - Test application
 - A/B Testing
 - Hotjar
 - Google Analytics
 - Sketching
 - Wireframe
 - Prototype
 - Figma
 - Adobe XD
 - Invision
 - Zeplin
 - Photoshop
 - Slack
 - Design Thinking
 - Agile methodologies
 - Scrum
 - Jira

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://mygameprojectdesign.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: UX Designer
   start: 2018
   end: Ongoing
   employer: Stefanini
   description: Stefanini is a private Brazilian multinational, service and software provider, for data processing and consulting, with more than 25,000 employees in 40 countries across the Americas, Europe, Australia, and Asia.
 - title: Community Manager
   start: 2017
   end: 2019
   employer: Gimmer
   description: Gimmer is an automated trading platform that offers bots which execute cryptocurrency trading operations such as lending, arbitrage, margin trading, etc.
 - title: UX Designer / Front end
   start: 2015
   end: 2016
   employer: Antar Qld
   description: ANTaR Qld is an independent, national network of organisations and individuals working in support of justice for Aboriginal and Torres Strait Islander peoples of Queensland, Australia, since 1997.
 - title: Art Director
   start: 2002
   end: 2014
   employer: Sinprafarmas
   description: Sinprafarmas is a labor union focused in defend the interests of the farmacists and drugstore workers.

#Education is required
education:
 - level: Associate Degree (A.Dg.)
   date: 2017
   subject: Internet Systems
   school: Faculty of Technology from Baixada Santista - FATEC
 - level: Bachelor of Science (B.Sc.)
   date: 2002
   subject: Publicity & Advertising
   school: Catholic University of Santos
 - level: Certificate (extencion course)
   date: 2015
   subject: IT and Computer Science
   school: Queensland University of Technology - QUT



#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/d13ffd884cb6aaca9dc6d859499048b6
   courses:
    - title: Agile meets Design Thinking
      link: https://www.coursera.org/learn/uva-darden-getting-started-agile?
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
      date: February 12, 2019
    - title: Human-Centered Design
      link: https://www.coursera.org/learn/human-computer-interaction?
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
      date: Ongoing
    - title: UX by Design Circuit
      link: https://www.designcircuit.co/
      optionalimage: https://i.imgur.com/KUocDuZ.png
      date: Ongoing
    - title: Responsive Webdesign
      link: https://www.freecodecamp.org/certification/biarox/responsive-web-design
      optionalimage: https://i.imgur.com/M5D8e17.png
      date: April 11, 2019


#List of interesting Github repo/projects to include - optional
github:
 - biarox/biarox.github.io
 - biarox/seguran

#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://avatars0.githubusercontent.com/u/1934896?s=460&v=4
   

intro: |
  <h1>Hi I'm Beatriz Marques,</h1> 
  <h1>UX designer.</h1>
  <p>I’m passionate about creating usable digital products and I love to work as a team.</p>
  <p>I have 4 years experience as a User Experience Designer and I'm working as a Graphic Designer since 2002.</p>
#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
    <h4><strong>Lean Inception + Design Thinking = Deep Dive</strong>:</h4> 
    <div>
    <h2>I participated in the process of development of a new product for a Brazilian payment institution.</h2>
    <p>I joined the development of this product since the beginning, which allowed me to contribute to the key features by matching the user needs and the business needs.</p>
    </div>
    <div>
    <ul>
    <li>It was a new product focused on the payment of car tolls and debts. It required some study of the Brazilian Federal laws regarding payment and research of the law from each specific state.</li>
    <li>The target audience was people that own a vehicle (cars only) and had any debts to be paid.</li>
    <li>The product was created to make the payment easier by allowing the car owners to pay their debts in instalments.</li>
    <li>The challenge was to ideate, prototype and test an MVP in a small state and after that expand the business to the entire country.</li>
    <li>My role was to support the Agile Coach in the meetings, helping with the applied methodologies, using post-its, gathering the attention of the business crew, maintaining a productive environment.</li>
    <li>I also created and delivered an interactive mockup at the end of the process using Figma.</li>
    </ul>
    </div>

    <div>
    <h2>Personas</h2>
    <p>Based on the interviews/workshop we set up twelve personas. We referred to them throughout the entire product concept process.</p>
    <ul>
    <li>We listed all the users that will have direct contact with the system, from the stakeholders, finance to the final user.</li>
    <li>We used the personas to determine what each user needed from the system, and found out how many user roles were necessary to log in to the system as well.</li>
    </ul>
    </div>

    <div>
    <h2>User Journey</h2>
    <p>We mapped out the users’ steps to see how we could simplify their journey to help them reach their most important goals with the product.</p>
    </div>

    <div>
    <h2>Functionality mapping</h2>
    <p>To understand all the functionalities for each role we developed the functionality mapping.</p>
    <ul>
    <li>We prioritised each functionality by the difficulty of implementation and their importance in the product.</li>
    <li>We divided the functionalities and which roles required each one of them.</li>
    <li>We also marked the items that required more refinement for a future sprint.</li>
    </ul>
    </div>

    <div>
    <h2>Wireframes</h2>
    <p>At the beginning of my design process, I created wireframes for testing purposes.</p>
    <p>Pen and paper are my friends ^^</p>
    <ul>
    <li>After understanding the workflow of the system, I draw on paper how the components could be displayed on the screen.</li>
    <li>Then I moved to the development of a low fidelity prototype, using Figma.</li>
    </ul>
    </div>

    <div></div>

   <h4><strong>User Testing application</strong>:</h4> 
   <div>
   <h2>NGC (Negociação Grandes Contas) was an internal system focused on the big players in the financial market.</h2>
   </div>

   <div>
   <p>I managed to work on the conception of the idea, where I could assist from the beginning of this project. After understanding the business and the manager's problems I was able to apply some methodologies to help in the process of the development of this product.</p>
   <p>The initial state was an obsolete system that only worked using Internet Explorer 6, the layout and menu content was confusing and full of irrelevant information.</p>
    <ul>
    <li>The Product Owner didn't want to recycle any of the old system's database and wanted to build a brand new system with an intuitive and cleaner layout.</li>
    <li>The Development Team decided to use Angular 7 on the Front End so this decision made the whole UI prototype creation easier for me. I used the Angular components to create a simple and intuitive layout for the users.</li>
    <li>The company calls their credit card reader sellers "hunters", and they are the final user of the NGC. They used to complain about the complexity of how the information was displayed in the old system. With that, the managers decided to build a new, responsive, user-friendly system.</li>
    <li>The main challenge I faced was to maintain the UI two sprints ahead of the developers. It was not about the creative part of the process that I was concerned, but about validating it with the users. Sometimes they were very hard to reach and I had to validate the features with the PM and PO only. I'm not saying that this is a bad thing, but building a product based on human-centred Design is the key success, and nobody is better than the final user to validate the product.</li>
    </ul>
   </div>